
export const ADD_NEW_ART_PIECES_REQUEST = "ADD_NEW_ART_PIECES_REQUEST";
export const ADD_NEW_ART_PIECES_SUCCESS = "ADD_NEW_ART_PIECES_SUCCESS";
export const ADD_NEW_ART_PIECES_FAIL = "ADD_NEW_ART_PIECES_FAIL";

export const GET_ALL_ART_PIECESS_REQUEST = "GET_ALL_ART_PIECESS_REQUEST";
export const GET_ALL_ART_PIECESS_SUCCESS = "GET_ALL_ART_PIECESS_SUCCESS";
export const GET_ALL_ART_PIECESS_FAIL = "GET_ALL_ART_PIECESS_FAIL";






export const DELETE_ART_PIECES_REQUEST = "DELETE_ART_PIECES_REQUEST";
export const DELETE_ART_PIECES_SUCCESS = "DELETE_ART_PIECES_SUCCESS";
export const DELETE_ART_PIECES_FAIL = "DELETE_ART_PIECES_FAIL";
