const GET_ALL_ART_PIECES = "artPieces:GET_ALL_ART_PIECES";
const ADD_ART_PIECES = "artPieces:ADD_ART_PIECES";
const UPDATE_ART_PIECES = "artPieces:UPDATE_ART_PIECES";
const DELETE_ART_PIECES = "artPieces:DELETE_ART_PIECES";

module.exports = {
  GET_ALL_ART_PIECES,
  ADD_ART_PIECES,
  UPDATE_ART_PIECES,
  DELETE_ART_PIECES,
};
